### ISSUE TITLE
Component's delay not visible

### ISSUE THREAD

**Issue by z4nr34l** [vercel-labs/next-partial-prerendering#7]
Recommended products and customer reviews are loading same time.

Tested on:
- Latest macOS
- Latest Chrome
- Latest Safari

Looks like recommended products are waiting for reviews to render in place of skeleton.

**Comment by shaun-fitzgibbon** [comment]
Im also experiencing this, everything with pink dot seems to load all at once.
No different delays 

- macOs
- Brave browser latest

**Comment by z4nr34l** [comment]
Seems like it's solved now - issue there are ignored but in next.js repo they are living best life :D
